# Generated by Django 5.2.8 on 2025-11-17 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='is_online',
            field=models.BooleanField(default=False, help_text='Product is visible to customers on the website'),
        ),
    ]
