# Generated by Django 5.2.8 on 2025-11-17 13:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_order_payment_id_order_payment_method_order_status'),
        ('products', '0004_sale'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sales', to='orders.order'),
        ),
        migrations.AddField(
            model_name='sale',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
