# Generated by Django 5.2.8 on 2025-12-15 11:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_sale_order_sale_quantity'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductPriceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cost_price', models.DecimalField(decimal_places=2, help_text='Cost price at this point in time', max_digits=10)),
                ('selling_price', models.DecimalField(decimal_places=2, help_text='Selling price at this point in time', max_digits=10)),
                ('changed_at', models.DateTimeField(auto_now_add=True, help_text='When the price was changed')),
                ('reason', models.TextField(blank=True, help_text='Optional reason for the price change')),
                ('changed_by', models.ForeignKey(blank=True, help_text='User who made the price change', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_history', to='products.product')),
            ],
            options={
                'verbose_name': 'Product Price History',
                'verbose_name_plural': 'Product Price Histories',
                'ordering': ('-changed_at',),
                'indexes': [models.Index(fields=['product', '-changed_at'], name='products_pr_product_40293a_idx')],
            },
        ),
    ]
