# Generated by Django 5.2.8 on 2025-12-15 11:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_productpricehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.PositiveSmallIntegerField(choices=[(1, '1 Star'), (2, '2 Stars'), (3, '3 Stars'), (4, '4 Stars'), (5, '5 Stars')], help_text='Rate this product from 1 to 5 stars')),
                ('title', models.CharField(blank=True, help_text='Short title for your review', max_length=200)),
                ('comment', models.TextField(help_text='Your review of this product')),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('verified_purchase', models.BooleanField(default=False, help_text='Customer has purchased this product')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviews', to='products.product')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_reviews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Product Review',
                'verbose_name_plural': 'Product Reviews',
                'ordering': ('-created',),
                'indexes': [models.Index(fields=['product', '-created'], name='products_pr_product_71df89_idx'), models.Index(fields=['rating'], name='products_pr_rating_0e31b2_idx')],
                'unique_together': {('product', 'user')},
            },
        ),
    ]
